sudo: required
dist: trusty
language: python
python:
  - "3.4"
go:
  - "1.7"
services: mysql
env:
  - DJANGO=1.8
install:
  - mkdir solidity
  - cd solidity
  - mkdir solc
  - cd solc
  - wget https://ipfs.io/ipfs/QmTNN5EismWnAxMpQZjt8rYEUc7RsyGxvep2KZnMMfUqah -O solc
  - cd ../..
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go version
  - git clone git@github.com:OpenNetworking/go-ethereum.git
  - cd ./go-ethereum/ ; make evm
  - cd ..
  - pip install pep8
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database contract_server;'
  - cp ./contract_server/.env.default ./contract_server/.env
  - sed -i 's/^CONTRACT_SERVER_DB=.*/CONTRACT_SERVER_DB=contract_server/g' ./contract_server/.env
  - sed -i 's/^MYSQL_HOST=.*/MYSQL_HOST=127.0.0.1/g' ./contract_server/.env
  - sed -i 's/^MYSQL_PORT=.*/MYSQL_PORT=3306/g' ./contract_server/.env
  - sed -i 's/^MYSQL_USER=.*/MYSQL_USER=root/g' ./contract_server/.env
  - sed -i 's/^MYSQL_PASSWORD=.*/MYSQL_PASSWORD=/g' ./contract_server/.env
  - sed -i 's/^SERVER_CONFIG_ENV=.*/SERVER_CONFIG_ENV=contract_server.settings.production/g' ./contract_server/.env
  - sed -i 's/ALLOWED_HOSTS=.*/ALLOWED_HOSTS=/g' ./contract_server/.env
  - sed -i 's/LOG_PATH=.*/LOG_PATH=/g' ./contract_server/.env
  - sed -i 's/^SECRET_KEY=.*/SECRET_KEY=SECRET_KEY/g' ./contract_server/.env
  - pep8 --exclude=migrations --ignore=E123,E133,E226,E241,E242,E402,E501,W503 ./contract_server/
  - flake8 --exclude=migrations,settings,__init__.py --ignore=E123,E133,E226,E241,E242,E402,E501,W503 ./contract_server/
  - mkdir log
  - cd log
  - touch django.log
  - cd ..
  - git submodule init
  - git submodule update
  - echo "submodule done"
script:
  - cd ./contract_server
  - ./manage.py test
